language: java
jdk:
  - oraclejdk7
before_script: cd sweet-junit-runner
install:
  - mvn -f sweet-junit-runner/pom.xml test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn -f sweet-junit-runner/pom.xml test jacoco:report
after_success:
  - mvn -f sweet-junit-runner/pom.xml coveralls:report
